// Code generated by MockGen. DO NOT EDIT.
// Source: traffic_rollup.go
//
// Generated by this command:
//
//	mockgen -source traffic_rollup.go -destination mock/traffic_rollup.go -package mock_rollup_repo
//

// Package mock_rollup_repo is a generated GoMock package.
package mock_rollup_repo

import (
	context "context"
	reflect "reflect"

	rollup_entity "github.com/CodFrm/katch/internal/model/entity/rollup_entity"
	rollup_repo "github.com/CodFrm/katch/internal/repository/rollup_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTrafficRollupRepo is a mock of TrafficRollupRepo interface.
type MockTrafficRollupRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTrafficRollupRepoMockRecorder
	isgomock struct{}
}

// MockTrafficRollupRepoMockRecorder is the mock recorder for MockTrafficRollupRepo.
type MockTrafficRollupRepoMockRecorder struct {
	mock *MockTrafficRollupRepo
}

// NewMockTrafficRollupRepo creates a new mock instance.
func NewMockTrafficRollupRepo(ctrl *gomock.Controller) *MockTrafficRollupRepo {
	mock := &MockTrafficRollupRepo{ctrl: ctrl}
	mock.recorder = &MockTrafficRollupRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrafficRollupRepo) EXPECT() *MockTrafficRollupRepoMockRecorder {
	return m.recorder
}

// FindByBucket mocks base method.
func (m *MockTrafficRollupRepo) FindByBucket(ctx context.Context, upstreamID, bucket int64) (*rollup_entity.TrafficRollup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBucket", ctx, upstreamID, bucket)
	ret0, _ := ret[0].(*rollup_entity.TrafficRollup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBucket indicates an expected call of FindByBucket.
func (mr *MockTrafficRollupRepoMockRecorder) FindByBucket(ctx, upstreamID, bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBucket", reflect.TypeOf((*MockTrafficRollupRepo)(nil).FindByBucket), ctx, upstreamID, bucket)
}

// Prune mocks base method.
func (m *MockTrafficRollupRepo) Prune(ctx context.Context, before int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prune indicates an expected call of Prune.
func (mr *MockTrafficRollupRepoMockRecorder) Prune(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockTrafficRollupRepo)(nil).Prune), ctx, before)
}

// Save mocks base method.
func (m *MockTrafficRollupRepo) Save(ctx context.Context, row *rollup_entity.TrafficRollup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, row)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockTrafficRollupRepoMockRecorder) Save(ctx, row any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTrafficRollupRepo)(nil).Save), ctx, row)
}

// Sum mocks base method.
func (m *MockTrafficRollupRepo) Sum(ctx context.Context, from, to int64) (*rollup_entity.Totals, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sum", ctx, from, to)
	ret0, _ := ret[0].(*rollup_entity.Totals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sum indicates an expected call of Sum.
func (mr *MockTrafficRollupRepoMockRecorder) Sum(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sum", reflect.TypeOf((*MockTrafficRollupRepo)(nil).Sum), ctx, from, to)
}

// SumBySeries mocks base method.
func (m *MockTrafficRollupRepo) SumBySeries(ctx context.Context, q rollup_repo.SeriesQuery) ([]*rollup_repo.SeriesTotals, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumBySeries", ctx, q)
	ret0, _ := ret[0].([]*rollup_repo.SeriesTotals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumBySeries indicates an expected call of SumBySeries.
func (mr *MockTrafficRollupRepoMockRecorder) SumBySeries(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumBySeries", reflect.TypeOf((*MockTrafficRollupRepo)(nil).SumBySeries), ctx, q)
}

// SumByUpstream mocks base method.
func (m *MockTrafficRollupRepo) SumByUpstream(ctx context.Context, from, to int64) ([]*rollup_entity.Totals, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumByUpstream", ctx, from, to)
	ret0, _ := ret[0].([]*rollup_entity.Totals)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumByUpstream indicates an expected call of SumByUpstream.
func (mr *MockTrafficRollupRepoMockRecorder) SumByUpstream(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumByUpstream", reflect.TypeOf((*MockTrafficRollupRepo)(nil).SumByUpstream), ctx, from, to)
}
