// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/upstream_repo/upstream.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/upstream_repo/upstream.go -destination internal/repository/upstream_repo/mock/upstream.go -package mock_upstream_repo
//

// Package mock_upstream_repo is a generated GoMock package.
package mock_upstream_repo

import (
	context "context"
	reflect "reflect"

	upstream_entity "github.com/CodFrm/katch/internal/model/entity/upstream_entity"
	upstream_repo "github.com/CodFrm/katch/internal/repository/upstream_repo"
	gomock "go.uber.org/mock/gomock"
)

// MockUpstreamRepo is a mock of UpstreamRepo interface.
type MockUpstreamRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUpstreamRepoMockRecorder
	isgomock struct{}
}

// MockUpstreamRepoMockRecorder is the mock recorder for MockUpstreamRepo.
type MockUpstreamRepoMockRecorder struct {
	mock *MockUpstreamRepo
}

// NewMockUpstreamRepo creates a new mock instance.
func NewMockUpstreamRepo(ctrl *gomock.Controller) *MockUpstreamRepo {
	mock := &MockUpstreamRepo{ctrl: ctrl}
	mock.recorder = &MockUpstreamRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpstreamRepo) EXPECT() *MockUpstreamRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUpstreamRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUpstreamRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUpstreamRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockUpstreamRepo) Find(ctx context.Context, id int64) (*upstream_entity.Upstream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*upstream_entity.Upstream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUpstreamRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUpstreamRepo)(nil).Find), ctx, id)
}

// FindByHost mocks base method.
func (m *MockUpstreamRepo) FindByHost(ctx context.Context, host string) (*upstream_entity.Upstream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHost", ctx, host)
	ret0, _ := ret[0].(*upstream_entity.Upstream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHost indicates an expected call of FindByHost.
func (mr *MockUpstreamRepoMockRecorder) FindByHost(ctx, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHost", reflect.TypeOf((*MockUpstreamRepo)(nil).FindByHost), ctx, host)
}

// List mocks base method.
func (m *MockUpstreamRepo) List(ctx context.Context) ([]*upstream_entity.Upstream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*upstream_entity.Upstream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUpstreamRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUpstreamRepo)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockUpstreamRepo) Save(ctx context.Context, upstream *upstream_entity.Upstream) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, upstream)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUpstreamRepoMockRecorder) Save(ctx, upstream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUpstreamRepo)(nil).Save), ctx, upstream)
}

// MockRewriteConfigRepo is a mock of RewriteConfigRepo interface.
type MockRewriteConfigRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRewriteConfigRepoMockRecorder
	isgomock struct{}
}

// MockRewriteConfigRepoMockRecorder is the mock recorder for MockRewriteConfigRepo.
type MockRewriteConfigRepoMockRecorder struct {
	mock *MockRewriteConfigRepo
}

// NewMockRewriteConfigRepo creates a new mock instance.
func NewMockRewriteConfigRepo(ctrl *gomock.Controller) *MockRewriteConfigRepo {
	mock := &MockRewriteConfigRepo{ctrl: ctrl}
	mock.recorder = &MockRewriteConfigRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewriteConfigRepo) EXPECT() *MockRewriteConfigRepoMockRecorder {
	return m.recorder
}

// AdvanceGeneration mocks base method.
func (m *MockRewriteConfigRepo) AdvanceGeneration(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvanceGeneration", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdvanceGeneration indicates an expected call of AdvanceGeneration.
func (mr *MockRewriteConfigRepoMockRecorder) AdvanceGeneration(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvanceGeneration", reflect.TypeOf((*MockRewriteConfigRepo)(nil).AdvanceGeneration), ctx)
}

// Snapshot mocks base method.
func (m *MockRewriteConfigRepo) Snapshot(ctx context.Context) (*upstream_repo.RewriteConfigSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(*upstream_repo.RewriteConfigSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockRewriteConfigRepoMockRecorder) Snapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockRewriteConfigRepo)(nil).Snapshot), ctx)
}

// Transaction mocks base method.
func (m *MockRewriteConfigRepo) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockRewriteConfigRepoMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockRewriteConfigRepo)(nil).Transaction), ctx, fn)
}
