// Code generated by MockGen. DO NOT EDIT.
// Source: cache_object.go
//
// Generated by this command:
//
//	mockgen -source cache_object.go -destination mock/cache_object.go -package mock_cache_repo
//

// Package mock_cache_repo is a generated GoMock package.
package mock_cache_repo

import (
	context "context"
	reflect "reflect"

	cache_entity "github.com/CodFrm/katch/internal/model/entity/cache_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCacheObjectRepo is a mock of CacheObjectRepo interface.
type MockCacheObjectRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheObjectRepoMockRecorder
	isgomock struct{}
}

// MockCacheObjectRepoMockRecorder is the mock recorder for MockCacheObjectRepo.
type MockCacheObjectRepoMockRecorder struct {
	mock *MockCacheObjectRepo
}

// NewMockCacheObjectRepo creates a new mock instance.
func NewMockCacheObjectRepo(ctrl *gomock.Controller) *MockCacheObjectRepo {
	mock := &MockCacheObjectRepo{ctrl: ctrl}
	mock.recorder = &MockCacheObjectRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheObjectRepo) EXPECT() *MockCacheObjectRepoMockRecorder {
	return m.recorder
}

// CountByDigest mocks base method.
func (m *MockCacheObjectRepo) CountByDigest(ctx context.Context, digest string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByDigest", ctx, digest)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByDigest indicates an expected call of CountByDigest.
func (mr *MockCacheObjectRepoMockRecorder) CountByDigest(ctx, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByDigest", reflect.TypeOf((*MockCacheObjectRepo)(nil).CountByDigest), ctx, digest)
}

// CountByUpstream mocks base method.
func (m *MockCacheObjectRepo) CountByUpstream(ctx context.Context) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUpstream", ctx)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUpstream indicates an expected call of CountByUpstream.
func (mr *MockCacheObjectRepoMockRecorder) CountByUpstream(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUpstream", reflect.TypeOf((*MockCacheObjectRepo)(nil).CountByUpstream), ctx)
}

// Delete mocks base method.
func (m *MockCacheObjectRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheObjectRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheObjectRepo)(nil).Delete), ctx, id)
}

// DeleteExpired mocks base method.
func (m *MockCacheObjectRepo) DeleteExpired(ctx context.Context, id, before int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, id, before)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockCacheObjectRepoMockRecorder) DeleteExpired(ctx, id, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockCacheObjectRepo)(nil).DeleteExpired), ctx, id, before)
}

// EvictCandidates mocks base method.
func (m *MockCacheObjectRepo) EvictCandidates(ctx context.Context, limit int) ([]*cache_entity.CacheObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvictCandidates", ctx, limit)
	ret0, _ := ret[0].([]*cache_entity.CacheObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvictCandidates indicates an expected call of EvictCandidates.
func (mr *MockCacheObjectRepoMockRecorder) EvictCandidates(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvictCandidates", reflect.TypeOf((*MockCacheObjectRepo)(nil).EvictCandidates), ctx, limit)
}

// ExpiredBefore mocks base method.
func (m *MockCacheObjectRepo) ExpiredBefore(ctx context.Context, before int64, limit int) ([]*cache_entity.CacheObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpiredBefore", ctx, before, limit)
	ret0, _ := ret[0].([]*cache_entity.CacheObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpiredBefore indicates an expected call of ExpiredBefore.
func (mr *MockCacheObjectRepoMockRecorder) ExpiredBefore(ctx, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpiredBefore", reflect.TypeOf((*MockCacheObjectRepo)(nil).ExpiredBefore), ctx, before, limit)
}

// Find mocks base method.
func (m *MockCacheObjectRepo) Find(ctx context.Context, id int64) (*cache_entity.CacheObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*cache_entity.CacheObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockCacheObjectRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockCacheObjectRepo)(nil).Find), ctx, id)
}

// FindByKey mocks base method.
func (m *MockCacheObjectRepo) FindByKey(ctx context.Context, upstreamID int64, key string) (*cache_entity.CacheObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByKey", ctx, upstreamID, key)
	ret0, _ := ret[0].(*cache_entity.CacheObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByKey indicates an expected call of FindByKey.
func (mr *MockCacheObjectRepoMockRecorder) FindByKey(ctx, upstreamID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKey", reflect.TypeOf((*MockCacheObjectRepo)(nil).FindByKey), ctx, upstreamID, key)
}

// ListByPrefix mocks base method.
func (m *MockCacheObjectRepo) ListByPrefix(ctx context.Context, upstreamID int64, prefix string) ([]*cache_entity.CacheObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPrefix", ctx, upstreamID, prefix)
	ret0, _ := ret[0].([]*cache_entity.CacheObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPrefix indicates an expected call of ListByPrefix.
func (mr *MockCacheObjectRepoMockRecorder) ListByPrefix(ctx, upstreamID, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPrefix", reflect.TypeOf((*MockCacheObjectRepo)(nil).ListByPrefix), ctx, upstreamID, prefix)
}

// ListByUpstream mocks base method.
func (m *MockCacheObjectRepo) ListByUpstream(ctx context.Context, upstreamID int64) ([]*cache_entity.CacheObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUpstream", ctx, upstreamID)
	ret0, _ := ret[0].([]*cache_entity.CacheObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUpstream indicates an expected call of ListByUpstream.
func (mr *MockCacheObjectRepoMockRecorder) ListByUpstream(ctx, upstreamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUpstream", reflect.TypeOf((*MockCacheObjectRepo)(nil).ListByUpstream), ctx, upstreamID)
}

// ListTreeDirs mocks base method.
func (m *MockCacheObjectRepo) ListTreeDirs(ctx context.Context, opt *cache_entity.TreeOption) ([]*cache_entity.TreeDir, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTreeDirs", ctx, opt)
	ret0, _ := ret[0].([]*cache_entity.TreeDir)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeDirs indicates an expected call of ListTreeDirs.
func (mr *MockCacheObjectRepoMockRecorder) ListTreeDirs(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeDirs", reflect.TypeOf((*MockCacheObjectRepo)(nil).ListTreeDirs), ctx, opt)
}

// ListTreeObjects mocks base method.
func (m *MockCacheObjectRepo) ListTreeObjects(ctx context.Context, opt *cache_entity.TreeOption) ([]*cache_entity.CacheObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTreeObjects", ctx, opt)
	ret0, _ := ret[0].([]*cache_entity.CacheObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeObjects indicates an expected call of ListTreeObjects.
func (mr *MockCacheObjectRepoMockRecorder) ListTreeObjects(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeObjects", reflect.TypeOf((*MockCacheObjectRepo)(nil).ListTreeObjects), ctx, opt)
}

// PromoteImmutable mocks base method.
func (m *MockCacheObjectRepo) PromoteImmutable(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteImmutable", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PromoteImmutable indicates an expected call of PromoteImmutable.
func (mr *MockCacheObjectRepoMockRecorder) PromoteImmutable(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteImmutable", reflect.TypeOf((*MockCacheObjectRepo)(nil).PromoteImmutable), ctx, id)
}

// Save mocks base method.
func (m *MockCacheObjectRepo) Save(ctx context.Context, object *cache_entity.CacheObject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, object)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCacheObjectRepoMockRecorder) Save(ctx, object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCacheObjectRepo)(nil).Save), ctx, object)
}

// Search mocks base method.
func (m *MockCacheObjectRepo) Search(ctx context.Context, opt *cache_entity.SearchOption) ([]*cache_entity.CacheObject, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, opt)
	ret0, _ := ret[0].([]*cache_entity.CacheObject)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Search indicates an expected call of Search.
func (mr *MockCacheObjectRepoMockRecorder) Search(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockCacheObjectRepo)(nil).Search), ctx, opt)
}

// SearchTree mocks base method.
func (m *MockCacheObjectRepo) SearchTree(ctx context.Context, opt *cache_entity.TreeSearchOption) ([]*cache_entity.CacheObject, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTree", ctx, opt)
	ret0, _ := ret[0].([]*cache_entity.CacheObject)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchTree indicates an expected call of SearchTree.
func (mr *MockCacheObjectRepoMockRecorder) SearchTree(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTree", reflect.TypeOf((*MockCacheObjectRepo)(nil).SearchTree), ctx, opt)
}

// SetPinned mocks base method.
func (m *MockCacheObjectRepo) SetPinned(ctx context.Context, id int64, pinned bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPinned", ctx, id, pinned)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPinned indicates an expected call of SetPinned.
func (mr *MockCacheObjectRepoMockRecorder) SetPinned(ctx, id, pinned any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPinned", reflect.TypeOf((*MockCacheObjectRepo)(nil).SetPinned), ctx, id, pinned)
}

// SizeByUpstream mocks base method.
func (m *MockCacheObjectRepo) SizeByUpstream(ctx context.Context) (map[int64]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SizeByUpstream", ctx)
	ret0, _ := ret[0].(map[int64]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SizeByUpstream indicates an expected call of SizeByUpstream.
func (mr *MockCacheObjectRepoMockRecorder) SizeByUpstream(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SizeByUpstream", reflect.TypeOf((*MockCacheObjectRepo)(nil).SizeByUpstream), ctx)
}

// StatByPrefix mocks base method.
func (m *MockCacheObjectRepo) StatByPrefix(ctx context.Context, upstreamID int64, prefix string) (*cache_entity.PrefixTreeStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatByPrefix", ctx, upstreamID, prefix)
	ret0, _ := ret[0].(*cache_entity.PrefixTreeStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatByPrefix indicates an expected call of StatByPrefix.
func (mr *MockCacheObjectRepoMockRecorder) StatByPrefix(ctx, upstreamID, prefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatByPrefix", reflect.TypeOf((*MockCacheObjectRepo)(nil).StatByPrefix), ctx, upstreamID, prefix)
}

// StatByUpstream mocks base method.
func (m *MockCacheObjectRepo) StatByUpstream(ctx context.Context) ([]*cache_entity.UpstreamTreeStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatByUpstream", ctx)
	ret0, _ := ret[0].([]*cache_entity.UpstreamTreeStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatByUpstream indicates an expected call of StatByUpstream.
func (mr *MockCacheObjectRepoMockRecorder) StatByUpstream(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatByUpstream", reflect.TypeOf((*MockCacheObjectRepo)(nil).StatByUpstream), ctx)
}

// StatTreeMatch mocks base method.
func (m *MockCacheObjectRepo) StatTreeMatch(ctx context.Context, opt *cache_entity.TreeMatchOption) (*cache_entity.TreeMatchStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatTreeMatch", ctx, opt)
	ret0, _ := ret[0].(*cache_entity.TreeMatchStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatTreeMatch indicates an expected call of StatTreeMatch.
func (mr *MockCacheObjectRepoMockRecorder) StatTreeMatch(ctx, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatTreeMatch", reflect.TypeOf((*MockCacheObjectRepo)(nil).StatTreeMatch), ctx, opt)
}

// TotalSize mocks base method.
func (m *MockCacheObjectRepo) TotalSize(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalSize", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalSize indicates an expected call of TotalSize.
func (mr *MockCacheObjectRepoMockRecorder) TotalSize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalSize", reflect.TypeOf((*MockCacheObjectRepo)(nil).TotalSize), ctx)
}

// Touch mocks base method.
func (m *MockCacheObjectRepo) Touch(ctx context.Context, id, at int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockCacheObjectRepoMockRecorder) Touch(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockCacheObjectRepo)(nil).Touch), ctx, id, at)
}
