// Code generated by MockGen. DO NOT EDIT.
// Source: setting.go
//
// Generated by this command:
//
//	mockgen -source setting.go -destination mock/setting.go -package mock_setting_repo
//

// Package mock_setting_repo is a generated GoMock package.
package mock_setting_repo

import (
	context "context"
	reflect "reflect"

	setting_entity "github.com/CodFrm/katch/internal/model/entity/setting_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingRepo is a mock of SettingRepo interface.
type MockSettingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSettingRepoMockRecorder
	isgomock struct{}
}

// MockSettingRepoMockRecorder is the mock recorder for MockSettingRepo.
type MockSettingRepoMockRecorder struct {
	mock *MockSettingRepo
}

// NewMockSettingRepo creates a new mock instance.
func NewMockSettingRepo(ctrl *gomock.Controller) *MockSettingRepo {
	mock := &MockSettingRepo{ctrl: ctrl}
	mock.recorder = &MockSettingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingRepo) EXPECT() *MockSettingRepoMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockSettingRepo) Find(ctx context.Context, key string) (*setting_entity.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, key)
	ret0, _ := ret[0].(*setting_entity.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSettingRepoMockRecorder) Find(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSettingRepo)(nil).Find), ctx, key)
}

// Save mocks base method.
func (m *MockSettingRepo) Save(ctx context.Context, setting *setting_entity.Setting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSettingRepoMockRecorder) Save(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSettingRepo)(nil).Save), ctx, setting)
}
