// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/event_repo/event.go
//
// Generated by this command:
//
//	mockgen -source internal/repository/event_repo/event.go -destination internal/repository/event_repo/mock/event.go -package mock_event_repo
//

// Package mock_event_repo is a generated GoMock package.
package mock_event_repo

import (
	context "context"
	reflect "reflect"

	event_entity "github.com/CodFrm/katch/internal/model/entity/event_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEventRepo) Create(ctx context.Context, event *event_entity.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEventRepoMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEventRepo)(nil).Create), ctx, event)
}

// List mocks base method.
func (m *MockEventRepo) List(ctx context.Context, limit int) ([]*event_entity.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, limit)
	ret0, _ := ret[0].([]*event_entity.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockEventRepoMockRecorder) List(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockEventRepo)(nil).List), ctx, limit)
}
