// Code generated by MockGen. DO NOT EDIT.
// Source: recent_request.go
//
// Generated by this command:
//
//	mockgen -source recent_request.go -destination mock/recent_request.go -package mock_request_log_repo
//

// Package mock_request_log_repo is a generated GoMock package.
package mock_request_log_repo

import (
	context "context"
	reflect "reflect"

	request_log_entity "github.com/CodFrm/katch/internal/model/entity/request_log_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestLogRepo is a mock of RequestLogRepo interface.
type MockRequestLogRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRequestLogRepoMockRecorder
	isgomock struct{}
}

// MockRequestLogRepoMockRecorder is the mock recorder for MockRequestLogRepo.
type MockRequestLogRepoMockRecorder struct {
	mock *MockRequestLogRepo
}

// NewMockRequestLogRepo creates a new mock instance.
func NewMockRequestLogRepo(ctrl *gomock.Controller) *MockRequestLogRepo {
	mock := &MockRequestLogRepo{ctrl: ctrl}
	mock.recorder = &MockRequestLogRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestLogRepo) EXPECT() *MockRequestLogRepoMockRecorder {
	return m.recorder
}

// ListRecent mocks base method.
func (m *MockRequestLogRepo) ListRecent(ctx context.Context, upstreamID int64, limit int) ([]*request_log_entity.RecentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecent", ctx, upstreamID, limit)
	ret0, _ := ret[0].([]*request_log_entity.RecentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecent indicates an expected call of ListRecent.
func (mr *MockRequestLogRepoMockRecorder) ListRecent(ctx, upstreamID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecent", reflect.TypeOf((*MockRequestLogRepo)(nil).ListRecent), ctx, upstreamID, limit)
}

// Prune mocks base method.
func (m *MockRequestLogRepo) Prune(ctx context.Context, before int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prune indicates an expected call of Prune.
func (mr *MockRequestLogRepoMockRecorder) Prune(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockRequestLogRepo)(nil).Prune), ctx, before)
}

// Save mocks base method.
func (m *MockRequestLogRepo) Save(ctx context.Context, rows []*request_log_entity.RecentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRequestLogRepoMockRecorder) Save(ctx, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRequestLogRepo)(nil).Save), ctx, rows)
}
