// Code generated by MockGen. DO NOT EDIT.
// Source: git_mirror.go
//
// Generated by this command:
//
//	mockgen -source git_mirror.go -destination mock/git_mirror.go -package mock_git_repo
//

// Package mock_git_repo is a generated GoMock package.
package mock_git_repo

import (
	context "context"
	reflect "reflect"

	git_entity "github.com/CodFrm/katch/internal/model/entity/git_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGitMirrorRepo is a mock of GitMirrorRepo interface.
type MockGitMirrorRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGitMirrorRepoMockRecorder
	isgomock struct{}
}

// MockGitMirrorRepoMockRecorder is the mock recorder for MockGitMirrorRepo.
type MockGitMirrorRepoMockRecorder struct {
	mock *MockGitMirrorRepo
}

// NewMockGitMirrorRepo creates a new mock instance.
func NewMockGitMirrorRepo(ctrl *gomock.Controller) *MockGitMirrorRepo {
	mock := &MockGitMirrorRepo{ctrl: ctrl}
	mock.recorder = &MockGitMirrorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitMirrorRepo) EXPECT() *MockGitMirrorRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockGitMirrorRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGitMirrorRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGitMirrorRepo)(nil).Delete), ctx, id)
}

// EvictCandidates mocks base method.
func (m *MockGitMirrorRepo) EvictCandidates(ctx context.Context, limit int) ([]*git_entity.GitMirror, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvictCandidates", ctx, limit)
	ret0, _ := ret[0].([]*git_entity.GitMirror)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EvictCandidates indicates an expected call of EvictCandidates.
func (mr *MockGitMirrorRepoMockRecorder) EvictCandidates(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvictCandidates", reflect.TypeOf((*MockGitMirrorRepo)(nil).EvictCandidates), ctx, limit)
}

// Find mocks base method.
func (m *MockGitMirrorRepo) Find(ctx context.Context, id int64) (*git_entity.GitMirror, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*git_entity.GitMirror)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockGitMirrorRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockGitMirrorRepo)(nil).Find), ctx, id)
}

// FindByRepo mocks base method.
func (m *MockGitMirrorRepo) FindByRepo(ctx context.Context, host, repo string) (*git_entity.GitMirror, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRepo", ctx, host, repo)
	ret0, _ := ret[0].(*git_entity.GitMirror)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRepo indicates an expected call of FindByRepo.
func (mr *MockGitMirrorRepoMockRecorder) FindByRepo(ctx, host, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRepo", reflect.TypeOf((*MockGitMirrorRepo)(nil).FindByRepo), ctx, host, repo)
}

// List mocks base method.
func (m *MockGitMirrorRepo) List(ctx context.Context) ([]*git_entity.GitMirror, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*git_entity.GitMirror)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGitMirrorRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGitMirrorRepo)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockGitMirrorRepo) Save(ctx context.Context, mirror *git_entity.GitMirror) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, mirror)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockGitMirrorRepoMockRecorder) Save(ctx, mirror any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGitMirrorRepo)(nil).Save), ctx, mirror)
}

// TotalSize mocks base method.
func (m *MockGitMirrorRepo) TotalSize(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalSize", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalSize indicates an expected call of TotalSize.
func (mr *MockGitMirrorRepoMockRecorder) TotalSize(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalSize", reflect.TypeOf((*MockGitMirrorRepo)(nil).TotalSize), ctx)
}

// Touch mocks base method.
func (m *MockGitMirrorRepo) Touch(ctx context.Context, id, at int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockGitMirrorRepoMockRecorder) Touch(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockGitMirrorRepo)(nil).Touch), ctx, id, at)
}
