// Code generated by MockGen. DO NOT EDIT.
// Source: rule.go
//
// Generated by this command:
//
//	mockgen -source rule.go -destination mock/rule.go -package mock_rule_repo
//

// Package mock_rule_repo is a generated GoMock package.
package mock_rule_repo

import (
	context "context"
	reflect "reflect"

	rule_entity "github.com/CodFrm/katch/internal/model/entity/rule_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessRuleRepo is a mock of AccessRuleRepo interface.
type MockAccessRuleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAccessRuleRepoMockRecorder
	isgomock struct{}
}

// MockAccessRuleRepoMockRecorder is the mock recorder for MockAccessRuleRepo.
type MockAccessRuleRepoMockRecorder struct {
	mock *MockAccessRuleRepo
}

// NewMockAccessRuleRepo creates a new mock instance.
func NewMockAccessRuleRepo(ctrl *gomock.Controller) *MockAccessRuleRepo {
	mock := &MockAccessRuleRepo{ctrl: ctrl}
	mock.recorder = &MockAccessRuleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessRuleRepo) EXPECT() *MockAccessRuleRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAccessRuleRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAccessRuleRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAccessRuleRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockAccessRuleRepo) Find(ctx context.Context, id int64) (*rule_entity.AccessRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*rule_entity.AccessRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAccessRuleRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAccessRuleRepo)(nil).Find), ctx, id)
}

// List mocks base method.
func (m *MockAccessRuleRepo) List(ctx context.Context) ([]*rule_entity.AccessRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*rule_entity.AccessRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAccessRuleRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAccessRuleRepo)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockAccessRuleRepo) Save(ctx context.Context, rule *rule_entity.AccessRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAccessRuleRepoMockRecorder) Save(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccessRuleRepo)(nil).Save), ctx, rule)
}
